# Generated by Django 5.1.1 on 2024-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
